### ISSUE TITLE
Share data between two controllers

### ISSUE THREAD

**Issue by cchacholiades** [brandonkboswell/AngularBooter#3]
I am trying to share information between two controllers. I think I can do so if I'll use `angular.factory()`. How can I create a factory with AngularBooter?

**Comment by brandonkboswell** [comment]
I haven't written code yet for Factories, but should be easy enough to do. Under the hood Factories and Services are the same thing, so I would recommend using Services until I have a minute to add factory code.

**Comment by cchacholiades** [comment]
Thanks for the suggestion. Yes, it is almost the same thing (they all are singletons). The only difference is that services can be constructor functions, while factories allow to run some code before an object is returned.
