### ISSUE TITLE
Modules with AngularBooter

### ISSUE THREAD

**Issue by cchacholiades** [brandonkboswell/AngularBooter#4]
I am trying to use [AngularStrap](http://mgcrea.github.io/angular-strap/) with AngularBooter. This requires to inject a module into the application, like so: 

```var app = angular.module('myApp', ['$strap.directives']);```

How can I make use of AngularStrap with AngularBooter? Can I achieve this by registering a configuration? 

```myApp.config.push([function() {
  console.log('config 2');
}]);```

**Comment by brandonkboswell** [comment]
Pretty close, if you need to have the AngularStrap dependency just push it into the dependencies array.

```
myApp = new AngularBooter('myApp');
myApp.dependencies.push('$strap.directives');
```

You can do this anytime prior to calling 
```
myApp.boot();
```

**Comment by cchacholiades** [comment]
I've done this as suggested by I get this error: 
```
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.14/$injector/modulerr?p0=myApp&p1=Error%3A%…20at%20d%20(http%3A%2F%2Flocalhost%3A8000%2Fjs%2Fangular.min.js%3A17%3A381)
```

This is how my scripts structure looks like: 
```
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular-strap/2.1.2/angular-strap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular-strap/2.1.2/angular-strap.tpl.min.js"></script>
    <script>
        window.myApp = new AngularBooter('myApp');
        myApp.dependencies.push('$strap.directives');
    </script>
```

And at the bottom of the document: 

```
    <script>
        myApp.boot();
    </script>
```
I've done this as suggested by I get this error: 
```
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.14/$injector/modulerr?p0=myApp&p1=Error%3A%…20at%20d%20(http%3A%2F%2Flocalhost%3A8000%2Fjs%2Fangular.min.js%3A17%3A381)
```

This is how my scripts structure looks like: 
```
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular-strap/2.1.2/angular-strap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular-strap/2.1.2/angular-strap.tpl.min.js"></script>
    <script>
        window.myApp = new AngularBooter('myApp');
        myApp.dependencies.push('$strap.directives');
    </script>
```

And at the bottom of the document: 

```
    <script>
        myApp.boot();
    </script>
```

**Comment by brandonkboswell** [comment]
I've had one other person note issues using Angular 1.3, when I get a minute I'll pull down a copy of 1.3 see if this is the culprit.

**Comment by cchacholiades** [comment]
So would you suggest using a newer angular version?

**Comment by brandonkboswell** [comment]
I've had success with this in Angular 1.2 or lower, but I'm not aware of a reason why it shouldn't work, just a few reports that it doesn't. I'll look into this.
